### ISSUE TITLE
Feature request: Show slow requests based on total time minus wait time

### ISSUE THREAD

**Issue by chazsconi** [skaes/logjam_app#5]
I have a configuration using a Rails app with Passenger. When Passenger gets blocked by some slow requests, I can easily see the impact on subsequent requests as they have a high wait time.  I can also find these subsequent requests by selecting the "Time" drop down and selecting wait time.

However it is not so easy to find the original slow requests that blocked Passenger.  To do this I would like to be able to find all slow requests based on their total time in Rails, i.e. Total time minus wait time.

**Comment by skaes** [comment]
this issue is now tracked here: https://github.com/skaes/logjam_core/issues/56
